.PHONY: all clean

CC = gcc
CFLAGS = -std=c99 -fopenmp -O3 -Wall -Wextra -pedantic -fPIC

INC = -Iinc/

OBJS = fft.o libchatfft.so 

all: $(OBJS)

fft.o: fft.c
	$(CC) -c $(CFLAGS) $(INC) $< -o $@

libchatfft.so: 
	$(CC) $(CFLAGS) -o $@ fft.o -shared

clean:
	rm -f $(OBJS)
